### ISSUE TITLE
There is actually something into nothing

### ISSUE THREAD

**Issue by origama** [asbestomolesto/nothing#3]
I cloned the repo and I was kinda disappointed when I found a file in it. Perhaps you should remove Readme.md?

**Comment by asbestomolesto** [comment]
We're actually working on that. Please be patient.

**Comment by asbestomolesto** [comment]
We got it. The repository itself DOES nothing, it doedn't mean that must contain nothing. So can contain something, but it does nothing. 
ISSUE SOLVED!!!
